name: mellow-ios
options:
  bundleIdPrefix: com.growgenie
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  organizationName: GrowGenie

packages:
  SwiftlyBeautiful:
    url: https://github.com/ltomaszewski/SwiftlyBeautiful
    branch: master
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.6.0   # or use `upToNextMajor: 11.6.0` if you prefer that syntax

targets:
  mellow-ios:
    type: application
    platform: iOS
    sources:
      - path: mellow-ios
    resources:
      - path: mellow-ios/Resources/Assets.xcassets
    dependencies:
      - package: SwiftlyBeautiful
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseFirestore
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: DRU4XTX272
        MARKETING_VERSION: 1.1.6
        CURRENT_PROJECT_VERSION: 42
        SWIFT_VERSION: 5.0
        ENABLE_PREVIEWS: YES
        INFOPLIST_FILE: mellow-ios/Info.plist
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: YES
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    info:
      path: mellow-ios/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen:
          UIImageName: ""
        UIAppFonts:
          - gothamrnd_light.otf
          - gothamrnd_medium.otf
          - gothamrnd_bold.otf
        ITSAppUsesNonExemptEncryption: NO

  mellow-iosTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: mellow-iosTests
    dependencies:
      - target: mellow-ios
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: DRU4XTX272
        SWIFT_VERSION: 5.0
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/mellow-ios.app/mellow-ios"
        PRODUCT_BUNDLE_IDENTIFIER: com.growgenie.mellow-iosTests
        GENERATE_INFOPLIST_FILE: YES

  mellow-iosUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: mellow-iosUITests
    dependencies:
      - target: mellow-ios
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: DRU4XTX272
        SWIFT_VERSION: 5.0
        TEST_TARGET_NAME: mellow-ios
        PRODUCT_BUNDLE_IDENTIFIER: com.growgenie.mellow-iosUITests
        GENERATE_INFOPLIST_FILE: YES

configurations:
  Debug:
    settings:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      ENABLE_TESTABILITY: YES
    xcconfig: Debug.xcconfig
  Release:
    settings:
      SWIFT_COMPILATION_MODE: wholemodule
      VALIDATE_PRODUCT: YES
    xcconfig: Release.xcconfig

schemes:
  mellow-ios:
    build:
      targets:
        mellow-ios: all
    test:
      targets:
        - name: mellow-iosTests
          parallelizable: true
          randomExecutionOrder: false
      run:
        config: Debug
    archive:
      config: Release

  mellow-iosUITests:
    build:
      targets:
        mellow-ios: all
    test:
      targets:
        - name: mellow-iosUITests
          parallelizable: true
          randomExecutionOrder: false
      run:
        config: Debug
    archive:
      config: Release
